version: "3.9"

services:
  php-env:
    image: ghcr.io/egdeconsulting/digikort:0.1.0
    build: .
    ports:
      - 8080:80

  digikort:
    image: mysql:latest
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: pass

  phpmyadmin:
    image: phpmyadmin:latest
    restart: always
    ports:
      - 3306:80
    environment:
      - PMA_ARBITRARY=1
